ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-noble"
FROM ghcr.io/vigno04/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/flowcase-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########

# Maltego wants a browser installed and the default is Firefox, Install Firefox
COPY ./src/ubuntu/install/firefox/ $INST_SCRIPTS/firefox/
COPY ./src/ubuntu/install/firefox/firefox.desktop $HOME/Desktop/
RUN bash $INST_SCRIPTS/firefox/install_firefox.sh && rm -rf $INST_SCRIPTS/firefox/

COPY ./src/ubuntu/install/maltego $INST_SCRIPTS/maltego/
RUN bash $INST_SCRIPTS/maltego/install_maltego.sh  && rm -rf $INST_SCRIPTS/maltego/

COPY ./src/ubuntu/install/maltego/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh


# Update the desktop environment to be optimized for a single application (Ubuntu Noble / Openbox)
COPY ./src/ubuntu/install/misc/single_app_openbox.sh $INST_SCRIPTS/misc/
RUN bash $INST_SCRIPTS/misc/single_app_openbox.sh && rm -f $INST_SCRIPTS/misc/single_app_openbox.sh
RUN rm -f /usr/bin/xfce4-panel /usr/bin/kasm-panel /usr/bin/tint2 /usr/bin/lxpanel


######### End Customizations ###########

#ADD ./src/common/scripts $STARTUPDIR
RUN $STARTUPDIR/set_user_permission.sh $HOME

RUN chown 1000:0 $HOME

ENV HOME /home/flowcase-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000

# trigger build
