ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-noble"
FROM ghcr.io/vigno04/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/flowcase-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
ENV START_DE=openbox
RUN apt-get update && apt-get install -y openbox && rm -rf /var/lib/apt/lists/*
WORKDIR $HOME

######### Customize Container Here ###########

COPY ./src/ubuntu/install/doom $INST_SCRIPTS/doom/
RUN bash $INST_SCRIPTS/doom/install_doom.sh  && rm -rf $INST_SCRIPTS/doom/

COPY ./src/ubuntu/install/doom/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh

# Update the desktop environment to be optimized for a single application (Ubuntu Noble / Openbox)
COPY ./src/ubuntu/install/misc/single_app_openbox.sh $INST_SCRIPTS/misc/
RUN bash $INST_SCRIPTS/misc/single_app_openbox.sh && rm -f $INST_SCRIPTS/misc/single_app_openbox.sh

######### End Customizations ###########

RUN chown 1000:0 $HOME

ENV HOME /home/flowcase-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000

# trigger build
