ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-noble"
FROM ghcr.io/vigno04/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/flowcase-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########


COPY ./src/ubuntu/install/remmina $INST_SCRIPTS/remmina/
RUN bash $INST_SCRIPTS/remmina/install_remmina.sh  && rm -rf $INST_SCRIPTS/remmina/

COPY ./src/ubuntu/install/remmina/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh
RUN chmod 755 $STARTUPDIR/custom_startup.sh

RUN mkdir -p $HOME/.config/remmina/
COPY ./src/ubuntu/install/remmina/remmina.pref $HOME/.config/remmina/remmina.pref
RUN chown -R 1000:1000 $HOME/.config/remmina/


# Update the desktop environment to be optimized for a single application (Ubuntu Noble / Openbox)
COPY ./src/ubuntu/install/misc/single_app_openbox.sh $INST_SCRIPTS/misc/
RUN bash $INST_SCRIPTS/misc/single_app_openbox.sh && rm -f $INST_SCRIPTS/misc/single_app_openbox.sh

######### End Customizations ###########

RUN chown 1000:0 $HOME

ENV HOME /home/flowcase-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000

# trigger build
